import Title from "../../ui/Title";
import List from "./List";

const Comments = () => {
  return (
    <article className="mt-36 flex max-w-375 flex-col items-center justify-center">
      <Title
        title="what people say"
        description="These comments and who posted them were completely generated by AI :)"
      >
        <p className="font-inter mt-5 text-center font-bold text-green">
          Kind words from{" "}
          <span className="georgia text-white italic">amazing people.</span>
        </p>
      </Title>
      <List />
    </article>
  );
};

export default Comments;
