const Title = () => {
  return (
    <section className="flex flex-col items-center">
      <p className="font-inter text-sm text-[#20B2A6]">WHAT PEOPLE SAY</p>
      <p className="font-inter mt-5 text-center text-5xl font-bold text-[#20B2A6]">
        Kind words from{" "}
        <span className="georgia text-white italic">amazing people.</span>
      </p>
      <p className="font-inter mt-5 w-11/12 text-center text-white/50">
        These comments and who posted them were completely generated by{" "}
        <span className="font-bold text-[#20b2a6]">AI :)</span>
      </p>
    </section>
  );
};

export default Title;
