
import Title from "../../../ui/Title";
import List from "./List";

const Comments = () => {
  return (
    <article
      id="testimonials"
      className="relative z-10 mt-36 flex max-w-375 scroll-m-22 flex-col items-center justify-center"
    >
      <Title
        title="what people say"
        description="These comments and who posted them were completely generated by AI :)"
      >
        <p className="text-green mt-5 text-center font-bold">
          Kind words from{" "}
          <span className="georgia text-white italic">amazing people.</span>
        </p>
      </Title>
      <List />
    </article>
  );
};

export default Comments;
