import Title from "../../../ui/Title";
import List from "./List";
import { motion } from 'motion/react';

const Comments = () => {
  return (
    <article
      id="testimonials"
      className="relative z-10 mt-36 flex max-w-375 scroll-m-22 flex-col items-center justify-center"
    >
      <motion.div
        initial={{ translateY: 20, opacity: 0, filter: "blur(2px)" }}
        whileInView={{ translateY: 0, opacity: 1, filter: "none" }}
        viewport={{ once: true }}
        transition={{ duration: 1, ease: "backIn" }}
      >
        <Title
          title="what people say"
          description="These comments and who posted them were completely generated by AI :)"
        >
          <p className="text-green mt-5 text-center font-bold">
            Kind words from{" "}
            <span className="georgia text-white italic">amazing people.</span>
          </p>
        </Title>
      </motion.div>
      <List />
    </article>
  );
};

export default Comments;
